### ISSUE TITLE
FastCGI, host, referer

### ISSUE THREAD

**Issue by nikolos89** [BendeRsay/docker#2]
стянул проект, прописал в енв конфиги, стартую проект.
расположил стартовым файлом битрикс_сетуп.пхп скачиваю архив с сайта 700 метров Управление сайтом Бизнес.
прописываю доступы к бд, логин, пароль, базу, жму далее.
происходит 1% заполнения базки и процесс рушится.

в конфиг файлах прописан 9000 порт:
fastcgi_pass php:9000;

![image](https://github.com/BendeRsay/docker/assets/39451364/d86de59c-f328-4069-8d76-1c7103d991d9)
![image](https://github.com/BendeRsay/docker/assets/39451364/7c15b8d2-ae56-4aec-bd7e-66d3405f6ca1)

![image](https://github.com/BendeRsay/docker/assets/39451364/b7c9e3ef-bc09-4fd6-9523-e1e55de1e799)
![image](https://github.com/BendeRsay/docker/assets/39451364/a649de31-6999-4adf-9b3c-722f9305be48)
![image](https://github.com/BendeRsay/docker/assets/39451364/bdb0b8d2-aead-42a6-8006-9837737708ed)

сама ошибка:
![image](https://github.com/BendeRsay/docker/assets/39451364/643dafb2-415c-4229-adae-7804f1983714)
![image](https://github.com/BendeRsay/docker/assets/39451364/6dc3dd29-cd2b-4dc2-89e2-da8904d2104e)

![image](https://github.com/BendeRsay/docker/assets/39451364/a9e1bfd7-9629-4a6c-9449-98207fb54c25)

отдельный вопрос вызывает переменная NGINX_HOST
до того, как сайт установился, что нужно туда прописывать? нужно ли устанавливать сайт просто на localhost или прописывать что-то в hosts уже нужно ?

**Comment by nikolos89** [comment]
так же, указывал mysql при установке, что бы сайт ходил в соседний контейнер, и складывал инфорацию в заранее созданную БД.
результат - тот же, ошибка "504 Gateway Time-out nginx"...

**Comment by nikolos89** [comment]
пробовал прописывать разные значения переменной..

![image](https://github.com/BendeRsay/docker/assets/39451364/71168736-2b0c-4f15-98d3-6e68b65a9855)

сервисы работают
![image](https://github.com/BendeRsay/docker/assets/39451364/b2e5dccf-367d-43d3-8957-69f6f41a3b9d)


мемкеш в .сеттингс.пхп - добавлял.

результат один и тот же, и всегда только 106 создаваемых таблиц внутри БД
![image](https://github.com/BendeRsay/docker/assets/39451364/329a7452-b392-43f5-8f0b-037223d044a2)

**Comment by BendeRsay** [comment]
> стянул проект, прописал в енв конфиги, стартую проект. расположил стартовым файлом битрикс_сетуп.пхп скачиваю архив с сайта 700 метров Управление сайтом Бизнес. прописываю доступы к бд, логин, пароль, базу, жму далее. происходит 1% заполнения базки и процесс рушится.
> 
> в конфиг файлах прописан 9000 порт: fastcgi_pass php:9000;
> 
> ![image](https://private-user-images.githubusercontent.com/39451364/291670487-d86de59c-f328-4069-8d76-1c7103d991d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTU2MTEsIm5iZiI6MTcwMzA1NTMxMSwicGF0aCI6Ii8zOTQ1MTM2NC8yOTE2NzA0ODctZDg2ZGU1OWMtZjMyOC00MDY5LThkNzYtMWM3MTAzZDk5MWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA2NTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZjY1YjdjZGE2NDg4OWI3OGUwMThhODU1NTBjZWE4M2Q0NWNkYzc5NmVlODQ1ZmM4OGVmNWJkOTRjZWQwNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xrzhZ4SuYZOHphmobYD088nBxdjSafFwoeAlIptm0V0) ![image](https://private-user-images.githubusercontent.com/39451364/291671093-7c15b8d2-ae56-4aec-bd7e-66d3405f6ca1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTU2MTEsIm5iZiI6MTcwMzA1NTMxMSwicGF0aCI6Ii8zOTQ1MTM2NC8yOTE2NzEwOTMtN2MxNWI4ZDItYWU1Ni00YWVjLWJkN2UtNjZkMzQwNWY2Y2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA2NTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNTk1YTk1MjhkNzk0NWFjN2I1YTk0MzM4ZjkzNGUwYmQ2Y2ZlNmExZWI5NzYyOTk0NGIxODU5YTUwMTQ3OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Ii7li6I0JEusaakDSGAZi8sPXpjloodS1cNLgbwYQ4)
> 
> ![image](https://private-user-images.githubusercontent.com/39451364/291666343-b7c9e3ef-bc09-4fd6-9523-e1e55de1e799.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTU2MTEsIm5iZiI6MTcwMzA1NTMxMSwicGF0aCI6Ii8zOTQ1MTM2NC8yOTE2NjYzNDMtYjdjOWUzZWYtYmMwOS00ZmQ2LTk1MjMtZTFlNTVkZTFlNzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA2NTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MDYyMzliZDdjYzZjOTAwNTUzYTgyODU1ZDBiZTM4ZTk3MDY3NTM5MTRiZDhhMzY0NzM2ZDYzYmNiMWIyMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3hL65H6dD6tbtFcHAkK_vi2IbMagyvdE6q8gSl1P0b0) ![image](https://private-user-images.githubusercontent.com/39451364/291666404-a649de31-6999-4adf-9b3c-722f9305be48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTU2MTEsIm5iZiI6MTcwMzA1NTMxMSwicGF0aCI6Ii8zOTQ1MTM2NC8yOTE2NjY0MDQtYTY0OWRlMzEtNjk5OS00YWRmLTliM2MtNzIyZjkzMDViZTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA2NTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYzE4MDZlODAwYTQ3MWJkY2FiMmQ1ZWY3ZTEwNjMyZTI0ODNmZDI3YjkzYzhiNWExZTUxMTIxMDQ1MjkyY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vw0Yzu2p3mu_N5ARYpn9ciBhUiWyMM1oAQk8Es9ty88) ![image](https://private-user-images.githubusercontent.com/39451364/291669044-bdb0b8d2-aead-42a6-8006-9837737708ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTU2MTEsIm5iZiI6MTcwMzA1NTMxMSwicGF0aCI6Ii8zOTQ1MTM2NC8yOTE2NjkwNDQtYmRiMGI4ZDItYWVhZC00MmE2LTgwMDYtOTgzNzczNzcwOGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA2NTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZTUwNzUxMGU1ODAwNTBlYmY0MjM2NGRkNDI1NWIwNzZmNTVhMGYyMWQ0OGY5YjhkZjk4OGZhOWM0OGE1MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-YBgkLjtBY6qk7wyeQtfRZI6Umz63S4KmgMVgRym9mQ)
> 
> сама ошибка: ![image](https://private-user-images.githubusercontent.com/39451364/291700522-643dafb2-415c-4229-adae-7804f1983714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTU2MTEsIm5iZiI6MTcwMzA1NTMxMSwicGF0aCI6Ii8zOTQ1MTM2NC8yOTE3MDA1MjItNjQzZGFmYjItNDE1Yy00MjI5LWFkYWUtNzgwNGYxOTgzNzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA2NTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYjk2ZjhkZmE4OGNiMDIwYjBjNjY3M2VjODQ3ZWUzOTA2NzQzZDIxMmEzYTcxMjFiNjVkZWU5ZGM0MTFlMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eQOwx8SkOgMQmTGvUSe9EvdnTDUKmQwQP0GHTyKXnFk) ![image](https://private-user-images.githubusercontent.com/39451364/291700576-6dc3dd29-cd2b-4dc2-89e2-da8904d2104e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTU2MTEsIm5iZiI6MTcwMzA1NTMxMSwicGF0aCI6Ii8zOTQ1MTM2NC8yOTE3MDA1NzYtNmRjM2RkMjktY2QyYi00ZGMyLTg5ZTItZGE4OTA0ZDIxMDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA2NTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MjhhZGI2N2NjZTQzZWU0NjhiZjQ5YTgwYjZmMGM4MDM2NDdhMmE1ODBkOTUwMzMzZmM3NjQzNWE2MjRhNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CuBN9h8MVp6Ai6SbYwmjPqJRB8ct6cjcBODWawn01yc)
> 
> ![image](https://private-user-images.githubusercontent.com/39451364/291700709-a9e1bfd7-9629-4a6c-9449-98207fb54c25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTU2MTEsIm5iZiI6MTcwMzA1NTMxMSwicGF0aCI6Ii8zOTQ1MTM2NC8yOTE3MDA3MDktYTllMWJmZDctOTYyOS00YTZjLTk0NDktOTgyMDdmYjU0YzI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA2NTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YjY5ODhmNmRlOWU2MWUzOTk3MTk4OGZjZTIyMTQ3MDQxYWE5NjZlMWE1MjQ2MzNlYjQwOTU3ZDY0YzJjZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j69XtxkLIevyrlUp2cn8QUdbLhRavkBVuL8InHuqQRE)
> 
> отдельный вопрос вызывает переменная NGINX_HOST до того, как сайт установился, что нужно туда прописывать? нужно ли устанавливать сайт просто на localhost или прописывать что-то в hosts уже нужно ?

1. Переменная NGINX_HOST - отвечает за домен, по которому вы будете ходить на сайт. Значение из нее так же нужно прописать в свой hosts. К примеру для windows в C:\Windows\System32\drivers\etc\hosts.
2. хост mysql надо указывать mysql. Это имя контейнера с MySql. Это Вы сделали правильно.
3. Судя по тому, что у вас ставится часть таблиц, все работает.
4. Битрикс не ставится на PHP выше 7.4. Вам нужно поменять версию на PHP 7.4, пересобрать образы make dc-build и запустить контейнеры make dc-up. После этого установить битрикс. Затем обновить его из админки. После переключить на PHP 8.2

**Comment by nikolos89** [comment]
добрый день!
большое спасибо за ответ!

обязательно буду пробовать.
есть ли какое-то универсальное решение. как пользоваться докером под Win ?
уже около 5 разных операционок ставил, результат один и тот же: после обновлений операционок Wsl теряет связь с сервером, не давая обновиться и запустить докера.

как правильнее поступить по вопросу поднятия докера ?

![image](https://github.com/BendeRsay/docker/assets/39451364/48d192ae-a3d9-46c9-84ed-36eeb427457d)
![image](https://github.com/BendeRsay/docker/assets/39451364/bf7ec8ec-deca-469a-bfc3-74c978704fca)

![image](https://github.com/BendeRsay/docker/assets/39451364/0e06bd19-6e24-4103-bc37-734519d57496)

1. установил ОС, накатываю wsl --install, 
2. перезагружаюсь
3. накатываю докер
4. перезагружаюсь
5. запускаю докер, всё работает отл.
6. обновляю ось,
7. перезагружаюсь, включаю докер - не работает. всё перепробовал уже, и удалять и устанавливать. без толку.  на скрине показан момент того, что докер был установлен, обновлялся, скачивался..

как быть? есть варианты ?

**Comment by BendeRsay** [comment]
У меня тоже бывали такие ошибки. Докер постоянно обновляется и исправляет их. Советую ставить ubuntu из магазина предложений windows, с ней меньше проблем.
![image](https://github.com/BendeRsay/docker/assets/8289955/d5eac05e-aedd-4dd2-9c23-484453caa8e6)

П.С. Данная проблема не относится к моему проекту, закрываю проблему.
